manifest:
  remotes:
    - name: darknao
      url-base: https://github.com/darknao
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: darknao
      revision: rgb-layer-25.08
      import: app/west.yml
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
  self:
    path: config
